
# mypy global options:
[tool.mypy]
show_column_numbers = true
show_error_context = false
ignore_missing_imports = true

# isort global options
[tool.isort]
profile = "black"

# pylint global options
[tool.pylint."MESSAGES CONTROL"]
disable = "fixme"

[tool.pylint.TYPECHECK]
generated-members = 'numpy.*, torch.*'

[tool.pylint.BASIC]
good-names = ["i", "j", "k", "e", "_", "f", "fp", "db", "df"]
